---
kind: Service
apiVersion: v1
metadata:
  name: happy-blue-green-active
spec:
  selector:
    app: happy-blue-green
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: happy-blue-green-preview
spec:
  selector:
    app: happy-blue-green
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
