apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: joyful-canary
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {}
        - analysis:
            templates:
            - templateName: success-rate
            args:
            - name: service-name
              value: joyful-canary
            # Set this to true for automatic rollbacks
            failureMode: Abort
        - setWeight: 60
        - pause: {duration: 1m}
        - setWeight: 80
        - pause: {duration: 5m}
  selector:
    matchLabels:
      app: joyful-canary
  template:
    metadata:
      labels:
        app: joyful-canary
    spec:
      containers:
        - name: joyful-canary
          image: sysadminexe/joyful-service:9b5659
          imagePullPolicy: Always
          env:
            - name: foo
              value: bar
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: joyful-canary
spec:
  ports:
    - port: 5000
      targetPort: 8080
  selector:
    app: joyful-canary

