apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: joyful-canary
spec:
  replicas: 5
  revisionHistoryLimit: 2
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 1m}
        - setWeight: 40
        - pause: {duration: 5m}
        - analysis:
            templates:
              - templateName: status-check
                clusterScope: true
            args:
              - name: service-name
                value: joyful-canary.joyful-service-canary.svc.cluster.local
        - setWeight: 60
        - pause: {duration: 10m}
        - setWeight: 80
        - pause: {duration: 20m}
  selector:
    matchLabels:
      app: joyful-canary
  template:
    metadata:
      labels:
        app: joyful-canary
    spec:
      containers:
        - name: joyful-canary
          image: sysadminexe/joyful-service:36b6ac
          imagePullPolicy: Always
          env:
            - name: foo
              value: bar
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
