apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 5s
    count: 2
    successCondition: result[0] >= 0.70
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus-service.monitoring:9090
        query: |
          sum(rate(http_requests_total{status=~"2.*", service="{{args.service-name}}"}[1m])) 
          / 
          sum(rate(http_requests_total{service="{{args.service-name}}"}[1m]))